name: Build Docker Images

on:
  push:
    branches: [ "test", "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Repo Name
        run: |
          echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Client image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          target: client
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:client
          build-args: |
            VITE_API_URL=http://178.154.219.101:3001/api

      - name: Build and push Server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          target: server
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:server